name: Python Black

# Run either when pushing directly to main/master or in a PR targeting main/master
on:
  push:
    branches:
      - master
      - main
    paths:
      - "**.py"
      - ".github/workflows/black.yml"
      - "poetry.lock"
      - "pyproject.toml"
  pull_request:
    branches:
      - master
      - main
    paths:
      - "**.py"
      - ".github/workflows/black.yml"
      - "poetry.lock"
      - "pyproject.toml"

# https://github.com/psf/black
jobs:
  format:
    runs-on: ubuntu-latest
    name: Black
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python environment
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: black
        uses: psf/black@stable
        with:
          options: "--check --verbose --diff --color"
