name: Python isort

on:
  push:
    branches:
      - main
    paths:
      - "**.py"
      - ".github/workflows/isort.yml"
      - "poetry.lock"
      - "pyproject.toml"
  pull_request:
    paths:
      - "**.py"
      - ".github/workflows/isort.yml"
      - "poetry.lock"
      - "pyproject.toml"

# https://github.com/marketplace/actions/python-isort
jobs:
  format:
    runs-on: ubuntu-latest
    name: isort
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python environment
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: isort
        uses: isort/isort-action@v1.1.0
